spring:
  profiles:
    active: dev #表示开发环境
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #使用artemis的配置
#  artemis:
#    mode: native
#    host: localhost
#    port: 61616
#    user: seizedays
#    password: seizedays123
    #使用activeMQ时的配置
  activemq:
    broker-url: tcp://localhost:61616

activemq:
  listener:
    enable: true

ipAddress:
  value: 127.0.0.1
feign:
  httpclient:
    enabled: true


