spring:
  profiles:
    #    active: info
    active: dev #表示开发环境
    # active: test
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  level:
    com.seizedays.semall.cart.mappers: debug
