server:
  port: 8080

#jdbc
spring:
  application:
    name: semall-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/semall_dev?useSSL=false&useTimeZone=true&serverTimeZone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: seizedays123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.seizedays.semall.user.mapper: debug
