spring:
  profiles:
    #    active: info
    active: dev #表示开发环境
    # active: test
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  activemq:
    broker-url: tcp://localhost:61616

activemq:
  listener:
    enable: true


logging:
  level:
    com.seizedays.semall.order.mappers: debug
